// flow-typed signature: 4f5f1b66d3830ed66b9813f43b93c533
// flow-typed version: <<STUB>>/express-prettify_v0.0.10/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-prettify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-prettify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-prettify/example/app' {
  declare module.exports: any;
}

declare module 'express-prettify/test/test-index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-prettify/example/app.js' {
  declare module.exports: $Exports<'express-prettify/example/app'>;
}
declare module 'express-prettify/index' {
  declare module.exports: $Exports<'express-prettify'>;
}
declare module 'express-prettify/index.js' {
  declare module.exports: $Exports<'express-prettify'>;
}
declare module 'express-prettify/test/test-index.js' {
  declare module.exports: $Exports<'express-prettify/test/test-index'>;
}
