// flow-typed signature: 450c64152c11bfd318e4ba7ec49a6fa5
// flow-typed version: <<STUB>>/flowdock-stream_v^1.1.1/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flowdock-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flowdock-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flowdock-stream/jsonparser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flowdock-stream/index' {
  declare module.exports: $Exports<'flowdock-stream'>;
}
declare module 'flowdock-stream/index.js' {
  declare module.exports: $Exports<'flowdock-stream'>;
}
declare module 'flowdock-stream/jsonparser.js' {
  declare module.exports: $Exports<'flowdock-stream/jsonparser'>;
}
