// flow-typed signature: 3d5d3a4a6bb95941d7358f3b99955bae
// flow-typed version: <<STUB>>/http_v0.0.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'http'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'http' {
  declare module.exports: any;
}
