// flow-typed signature: 21c82638a3572c193f9f9fc51aa69fcc
// flow-typed version: <<STUB>>/node-svn-ultimate_v^1.1.0/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-svn-ultimate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-svn-ultimate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-svn-ultimate/test/commands' {
  declare module.exports: any;
}

declare module 'node-svn-ultimate/test/createLocalSvnRepo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-svn-ultimate/index' {
  declare module.exports: $Exports<'node-svn-ultimate'>;
}
declare module 'node-svn-ultimate/index.js' {
  declare module.exports: $Exports<'node-svn-ultimate'>;
}
declare module 'node-svn-ultimate/test/commands.js' {
  declare module.exports: $Exports<'node-svn-ultimate/test/commands'>;
}
declare module 'node-svn-ultimate/test/createLocalSvnRepo.js' {
  declare module.exports: $Exports<'node-svn-ultimate/test/createLocalSvnRepo'>;
}
