// flow-typed signature: eebb9bde5289b90d4de04a1d06cff0fa
// flow-typed version: <<STUB>>/rally_v^2.1.2/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rally'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rally' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rally/dist/index' {
  declare module.exports: any;
}

declare module 'rally/dist/request' {
  declare module.exports: any;
}

declare module 'rally/dist/restapi' {
  declare module.exports: any;
}

declare module 'rally/dist/util/callbackify' {
  declare module.exports: any;
}

declare module 'rally/dist/util/query' {
  declare module.exports: any;
}

declare module 'rally/dist/util/ref' {
  declare module.exports: any;
}

declare module 'rally/examples/crud.callback' {
  declare module.exports: any;
}

declare module 'rally/examples/crud.promise' {
  declare module.exports: any;
}

declare module 'rally/examples/query.callback' {
  declare module.exports: any;
}

declare module 'rally/examples/query.promise' {
  declare module.exports: any;
}

declare module 'rally/lib/index' {
  declare module.exports: any;
}

declare module 'rally/lib/request' {
  declare module.exports: any;
}

declare module 'rally/lib/restapi' {
  declare module.exports: any;
}

declare module 'rally/lib/util/callbackify' {
  declare module.exports: any;
}

declare module 'rally/lib/util/query' {
  declare module.exports: any;
}

declare module 'rally/lib/util/ref' {
  declare module.exports: any;
}

declare module 'rally/spec/request.spec' {
  declare module.exports: any;
}

declare module 'rally/spec/restapi.spec' {
  declare module.exports: any;
}

declare module 'rally/spec/util/query.spec' {
  declare module.exports: any;
}

declare module 'rally/spec/util/ref.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rally/dist/index.js' {
  declare module.exports: $Exports<'rally/dist/index'>;
}
declare module 'rally/dist/request.js' {
  declare module.exports: $Exports<'rally/dist/request'>;
}
declare module 'rally/dist/restapi.js' {
  declare module.exports: $Exports<'rally/dist/restapi'>;
}
declare module 'rally/dist/util/callbackify.js' {
  declare module.exports: $Exports<'rally/dist/util/callbackify'>;
}
declare module 'rally/dist/util/query.js' {
  declare module.exports: $Exports<'rally/dist/util/query'>;
}
declare module 'rally/dist/util/ref.js' {
  declare module.exports: $Exports<'rally/dist/util/ref'>;
}
declare module 'rally/examples/crud.callback.js' {
  declare module.exports: $Exports<'rally/examples/crud.callback'>;
}
declare module 'rally/examples/crud.promise.js' {
  declare module.exports: $Exports<'rally/examples/crud.promise'>;
}
declare module 'rally/examples/query.callback.js' {
  declare module.exports: $Exports<'rally/examples/query.callback'>;
}
declare module 'rally/examples/query.promise.js' {
  declare module.exports: $Exports<'rally/examples/query.promise'>;
}
declare module 'rally/lib/index.js' {
  declare module.exports: $Exports<'rally/lib/index'>;
}
declare module 'rally/lib/request.js' {
  declare module.exports: $Exports<'rally/lib/request'>;
}
declare module 'rally/lib/restapi.js' {
  declare module.exports: $Exports<'rally/lib/restapi'>;
}
declare module 'rally/lib/util/callbackify.js' {
  declare module.exports: $Exports<'rally/lib/util/callbackify'>;
}
declare module 'rally/lib/util/query.js' {
  declare module.exports: $Exports<'rally/lib/util/query'>;
}
declare module 'rally/lib/util/ref.js' {
  declare module.exports: $Exports<'rally/lib/util/ref'>;
}
declare module 'rally/spec/request.spec.js' {
  declare module.exports: $Exports<'rally/spec/request.spec'>;
}
declare module 'rally/spec/restapi.spec.js' {
  declare module.exports: $Exports<'rally/spec/restapi.spec'>;
}
declare module 'rally/spec/util/query.spec.js' {
  declare module.exports: $Exports<'rally/spec/util/query.spec'>;
}
declare module 'rally/spec/util/ref.spec.js' {
  declare module.exports: $Exports<'rally/spec/util/ref.spec'>;
}
